FROM node:22-alpine AS build

ARG VITE_APP_NAME
ENV VITE_APP_NAME=$VITE_APP_NAME

ARG VITE_SEED_ADMIN_EMAIL
ENV VITE_SEED_ADMIN_EMAIL=$VITE_SEED_ADMIN_EMAIL

ARG VITE_SEED_ADMIN_PASSWORD
ENV VITE_SEED_ADMIN_PASSWORD=$VITE_SEED_ADMIN_PASSWORD

ARG VITE_ALLOW_PUBLIC_REGISTER
ENV VITE_ALLOW_PUBLIC_REGISTER=$VITE_ALLOW_PUBLIC_REGISTER

ARG VITE_API_BASE
ENV VITE_API_BASE=$VITE_API_BASE

WORKDIR /app

COPY ./src/package*.json ./
COPY ./src/package-lock.json* ./

RUN npm i

COPY ./src/ /app/

RUN npm run build

FROM nginx:alpine

WORKDIR /app

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./configs/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
